# Generated by Django 5.2.11 on 2026-04-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='site_name',
        ),
        migrations.AddField(
            model_name='language',
            name='flag_icon',
            field=models.CharField(blank=True, help_text='FontAwesome or Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address_ar',
            field=models.TextField(blank=True, verbose_name='Address (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_address_en',
            field=models.TextField(blank=True, verbose_name='Address (English)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_text_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='Footer Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Footer Text (English)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_ar',
            field=models.CharField(default='سناب فوليو', max_length=100, verbose_name='Site Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_en',
            field=models.CharField(default='SnapFolio', max_length=100, verbose_name='Site Name (English)'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='technologies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='service',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='technologies',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('slug', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('slug', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('slug', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='portfoliocategory',
            unique_together={('slug', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('slug', 'language')},
        ),
    ]
