# Generated by Django 5.2.11 on 2026-04-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogcategory_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('rating', models.IntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment (Optional)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.portfolio')),
            ],
            options={
                'verbose_name': 'Project Rating',
                'verbose_name_plural': 'Project Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('portfolio', 'email')},
            },
        ),
    ]
